### ISSUE TITLE
Deploy mech broken

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#313]
`make deploy` leads to 500 error on prod because of error in `front/build` code shipping

```
# dcp logs app
se-python                | ValueError: The file 'js/index.min.js' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7ff92563ce80>.
```

**Comment by artemiy312** [comment]
@duker33 this is because the "deploy" recipe does not create static files

**Comment by duker33** [comment]
@artemiy312 , y, and it does not create them because `fidals/se-python:prod` doesn't contain sources at `front/build` folder. Doesn't contain because of mistake in volumes structure.
Fixed it at pull#300

**Comment by duker33** [comment]
now we have problem to discuss https://github.com/fidals/shopelectro/pull/301#discussion_r192407331
Let's do it here, i'll write comment soon

**Comment by duker33** [comment]
@artemiy, got your bug reproduction.
We have problem with `front/build` folder delivery throw fidals/se:prod image.
Removed docker-compose code and appended `app/Dockerfile.prod` one. See PR binded to this task plz

**Comment by duker33** [comment]
@artemiy312 , tried to reproduce. And you are right: `fidals/se:prod` image contains non-empty `front/build` folder.
I've got empty directory inside image because of broken drone.

But we should do right actions to leave folder filled. Pretty in this secuence:
- rm -rf front/build
- dc rm -f app && dcp rm -f app
- gulp build
- rm images (for cleanup)
- build python-dev python-prod

If we miss smth, we have risk to get empty or stale front/build directory. I'll add `prepare-deploy` make recipe

**Comment by artemiy312** [comment]
@duker33 
> I've got empty directory inside image because of broken drone.

It would be nice to fix drone pipelines, because "prepare-deploy" receipt does not fix this issue

**Comment by duker33** [comment]
@artemiy312 , it gives us possibility to deploy.
We have #321 task to fix drone

**Comment by duker33** [comment]
worked at May for astro hours
